package pl.mftau.mftau.ui.theme

import androidx.compose.ui.graphics.Color

val mf_tau_light_primary = Color(0xFF542809)
val mf_tau_light_secondary = Color(0xFF803D09)
val mf_tau_dark_primary = Color(0xFF854E27)
val mf_tau_dark_secondary = Color(0xFF9A694B)

// LIGHT
val md_theme_light_primary = Color(0xFF96480D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC9)
val md_theme_light_onPrimaryContainer = Color(0xFF321200)
val md_theme_light_secondary = Color(0xFF765847)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBC9)
val md_theme_light_onSecondaryContainer = Color(0xFF2B1609)
val md_theme_light_tertiary = Color(0xFF96490C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onTertiaryContainer = Color(0xFF321200)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A17)
val md_theme_light_surfaceVariant = Color(0xFFF4DED4)
val md_theme_light_onSurfaceVariant = Color(0xFF52443C)
val md_theme_light_outline = Color(0xFF85746B)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEE9)
val md_theme_light_inverseSurface = Color(0xFF362F2C)
val md_theme_light_inversePrimary = Color(0xFFFFB68C)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF96480D)
val md_theme_light_outlineVariant = Color(0xFFD7C2B8)
val md_theme_light_scrim = Color(0xFF000000)

// DARK
val md_theme_dark_primary = Color(0xFFFFB68C)
val md_theme_dark_onPrimary = Color(0xFF522300)
val md_theme_dark_primaryContainer = Color(0xFF753400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_secondary = Color(0xFFE5BFAA)
val md_theme_dark_onSecondary = Color(0xFF432B1C)
val md_theme_dark_secondaryContainer = Color(0xFF5C4131)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_tertiary = Color(0xFFFFB68B)
val md_theme_dark_onTertiary = Color(0xFF522300)
val md_theme_dark_tertiaryContainer = Color(0xFF753400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A17)
val md_theme_dark_onBackground = Color(0xFFECE0DB)
val md_theme_dark_surface = Color(0xFF201A17)
val md_theme_dark_onSurface = Color(0xFFECE0DB)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C2B8)
val md_theme_dark_outline = Color(0xFF9F8D84)
val md_theme_dark_inverseOnSurface = Color(0xFF201A17)
val md_theme_dark_inverseSurface = Color(0xFFECE0DB)
val md_theme_dark_inversePrimary = Color(0xFF96480D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB68C)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF000000)

// MEETINGS
val MeetingType1Color1 = Color(0xff64ff11)
val MeetingType1Color2 = Color(0xff4cc10d)
val MeetingType1Color3 = Color(0xff378c09)
val MeetingType2Color1 = Color(0xff2d7eff)
val MeetingType2Color2 = Color(0xff205ec1)
val MeetingType2Color3 = Color(0xff154187)
val MeetingType3Color1 = Color(0xffff5b5b)
val MeetingType3Color2 = Color(0xffc64545)
val MeetingType3Color3 = Color(0xff993535)